

import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";

import styles from "../styles.module.scss";

export default function New_password() {
  const [isAuthenticate, setIsAuthenticate] = useState(false);

  const router = useRouter();

  async function handleResetPassword() {
    setIsAuthenticate(true);
    await router.push("/reset_password/token");
  }

  return (
    <>
      <Head>
        <title>Recuperar senha | eFunny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main>
          <section>
            <span>
              Insira nova senha 
            </span>
            <p> nova senha </p>
          </section>
          <input type="password" name="password" placeholder="******" />
          <button type="button" onClick={handleResetPassword}>
            Confirmar
          </button>
        </main>
      </div>
    </>
  );
}
