import Head from "next/head";
import { useEffect, useState } from "react";
import { AppLoading } from "../../components/AppLoading";
import styles from "./styles.module.scss";

export default function Home() {
  const [appIsLoading, setAppIsLoading] = useState<boolean>(true);

  useEffect(() => {
    setTimeout(async () => {
      setAppIsLoading(false);
    }, 3000);
  }, []);

  return (
    <>
      <Head>
        <title>eFunny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {appIsLoading ? (
        <AppLoading />
      ) : (
        <main className={styles.container}>
          <h1>Página Home que está no [unfile]</h1>
        </main>
      )}
    </>
  );
}
