import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Form } from "../../components/form";

import { FormButton } from "../../components/form/button";
import { FormInput } from "../../components/form/formInput";

import styles from "./authentication.module.scss";

export default function Authentication() {
  const [isAuthenticate, setIsAuthenticate] = useState(false);

  const router = useRouter();

  async function handleAuthenticate() {
    setIsAuthenticate(true);
    await router.push("/");
  }

  useEffect(() => {
    return () => setIsAuthenticate(false);
  }, []);

  return (
    <>
      <Head>
        <title>Login | eFunny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main>
          <div>
            <h1>Entrar na plataforma</h1>
          </div>
          <Form method="POST" onSubmit={handleAuthenticate}>
            <FormInput
              label="Nome de usuário"
              htmlFor="username"
              id="username"
              autoComplete="email"
            />
            <FormInput
              spanLabel="esqueci a senha"
              spanLabelHref="/reset_password"
              label="Senha"
              htmlFor="password"
              id="password"
              type="password"
              autoComplete="current-password"
            />

            <FormButton
              isLoading={isAuthenticate}
              type="submit"
              text="Entrar"
            />
          </Form>
          <footer>
            <p>
              Novo no eFunny?{" "}
              <Link href="/session" passHref>
                Cadastrar-se
              </Link>
            </p>
          </footer>
        </main>
      </div>
    </>
  );
}
