import Head from "next/head";
import Link from "next/link";
import { Form } from "../../components/form";

import { FormButton } from "../../components/form/button";
import { FormInput } from "../../components/form/formInput";

import styles from "../../styles/pages/sessions/Authentication.module.scss";

export default function Authentication() {
  return (
    <>
      <Head>
        <title>Login | e-funny</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <main>
          <div>
            <h1>Entrar na plataforma</h1>
          </div>
          <Form method="POST" onSubmit={() => {}}>
            <FormInput
              label="Email ou username"
              htmlFor="username"
              id="username"
              autoComplete="email"
            />
            <FormInput
              spanLabel="esqueci a senha"
              spanLabelHref="/reset_password"
              label="Senha"
              htmlFor="password"
              id="password"
              type="password"
              autoComplete="current-password"
            />

            <FormButton isLoading={false} type="submit" text="Entrar" />
          </Form>
          <footer>
            <p>
              New to e-funny?{" "}
              <Link href="/session" passHref>
                Sign up
              </Link>
            </p>
          </footer>
        </main>
      </div>
    </>
  );
}
